openapi: 3.2.0
info:
  contact:
    email: info@portainer.io
  description: Portainer API is an HTTP API served by Portainer.
  license:
    name: zlib
    url: https://github.com/portainer/portainer/blob/develop/LICENSE
  title: PortainerCE Docker API
  version: 2.39.1
servers:
- url: /api
tags:
- description: Manage Docker resources
  name: docker
paths:
  /docker/{environmentId}/containers/{containerId}/gpus:
    get:
      description: '**Access policy**:'
      operationId: dockerContainerGpusInspect
      parameters:
      - description: Environment identifier
        in: path
        name: environmentId
        required: true
        schema:
          type: integer
      - description: Container identifier
        in: path
        name: containerId
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/containers.containerGpusResponse'
        '400':
          description: Bad request
        '404':
          description: Environment or container not found
        '500':
          description: Internal server error
      security:
      - jwt: []
      summary: Fetch container gpus data
      tags:
      - docker
  /docker/{environmentId}/dashboard:
    get:
      description: '**Access policy**: restricted'
      operationId: dockerDashboard
      parameters:
      - description: Environment identifier
        in: path
        name: environmentId
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/docker.dashboardResponse'
        '400':
          description: Bad request
        '500':
          description: Internal server error
      security:
      - jwt: []
      summary: Get counters for the dashboard
      tags:
      - docker
  /docker/{environmentId}/images:
    get:
      description: '**Access policy**:'
      operationId: dockerImagesList
      parameters:
      - description: Environment identifier
        in: path
        name: environmentId
        required: true
        schema:
          type: integer
      - description: Include image usage information
        in: query
        name: withUsage
        schema:
          type: boolean
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/images.ImageResponse'
                type: array
        '400':
          description: Bad request
        '500':
          description: Internal server error
      security:
      - jwt: []
      summary: Fetch images
      tags:
      - docker
components:
  schemas:
    stats.ContainerStats:
      properties:
        healthy:
          type: integer
        running:
          type: integer
        stopped:
          type: integer
        total:
          type: integer
        unhealthy:
          type: integer
      type: object
    containers.containerGpusResponse:
      properties:
        gpus:
          type: string
      type: object
    images.ImageResponse:
      properties:
        created:
          type: integer
        id:
          type: string
        nodeName:
          type: string
        size:
          type: integer
        tags:
          items:
            type: string
          type: array
        used:
          description: 'Used is true if the image is used by at least one container

            supplied only when withUsage is true'
          type: boolean
      type: object
    docker.dashboardResponse:
      properties:
        containers:
          $ref: '#/components/schemas/stats.ContainerStats'
        images:
          $ref: '#/components/schemas/docker.imagesCounters'
        networks:
          type: integer
        services:
          type: integer
        stacks:
          type: integer
        volumes:
          type: integer
      type: object
    docker.imagesCounters:
      properties:
        size:
          type: integer
        total:
          type: integer
      type: object
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: X-API-KEY
      type: apiKey
    jwt:
      in: header
      name: Authorization
      type: apiKey
