openapi: 3.2.0
info:
  contact:
    email: info@portainer.io
  description: Portainer API is an HTTP API served by Portainer.
  license:
    name: zlib
    url: https://github.com/portainer/portainer/blob/develop/LICENSE
  title: PortainerCE Backup API
  version: 2.39.1
servers:
- url: /api
tags:
- description: Manage backups
  name: Backup
paths:
  /backup:
    post:
      description: 'Creates an archive with a system data snapshot that could be used to restore the system.

        **Access policy**: admin'
      operationId: Backup
      responses:
        '200':
          description: Success
        '400':
          description: Invalid request
        '500':
          description: Server error
      security:
      - ApiKeyAuth: []
      - jwt: []
      summary: Creates an archive with a system data snapshot that could be used to restore…
      tags:
      - Backup
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/backup.backupPayload'
        description: An object contains the password to encrypt the backup with
  /restore:
    post:
      description: 'Triggers a system restore using provided backup file

        **Access policy**: public'
      operationId: Restore
      responses:
        '200':
          description: Success
        '400':
          description: Invalid request
        '500':
          description: Server error
      summary: Triggers a system restore using provided backup file
      tags:
      - Backup
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/backup.restorePayload'
        description: Restore request payload
        required: true
components:
  schemas:
    backup.restorePayload:
      properties:
        FileContent:
          items:
            type: integer
          type: array
        FileName:
          type: string
        Password:
          type: string
      type: object
    backup.backupPayload:
      properties:
        Password:
          type: string
      type: object
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: X-API-KEY
      type: apiKey
    jwt:
      in: header
      name: Authorization
      type: apiKey
