openapi: 3.2.0
info:
  contact:
    email: info@portainer.io
  description: Portainer API is an HTTP API served by Portainer.
  license:
    name: zlib
    url: https://github.com/portainer/portainer/blob/develop/LICENSE
  title: PortainerCE Roles API
  version: 2.39.1
servers:
- url: /api
tags:
- description: Manage roles
  name: Roles
paths:
  /roles:
    get:
      description: 'List all roles available for use

        **Access policy**: administrator'
      operationId: RoleList
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/portainer.Role'
                type: array
        '500':
          description: Server error
      security:
      - ApiKeyAuth: []
      - jwt: []
      summary: List roles
      tags:
      - Roles
components:
  schemas:
    portainer.Role:
      properties:
        Authorizations:
          allOf:
          - $ref: '#/components/schemas/portainer.Authorizations'
          description: Authorizations associated to a role
        Description:
          description: Role description
          example: Read-only access of all resources in an environment(endpoint)
          type: string
        Id:
          description: Role Identifier
          example: 1
          type: integer
        Name:
          description: Role name
          example: HelpDesk
          type: string
        Priority:
          type: integer
      type: object
    portainer.Authorizations:
      additionalProperties:
        type: boolean
      type: object
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: X-API-KEY
      type: apiKey
    jwt:
      in: header
      name: Authorization
      type: apiKey
