openapi: 3.2.0
info:
  contact:
    email: info@portainer.io
  description: Portainer API is an HTTP API served by Portainer.
  license:
    name: zlib
    url: https://github.com/portainer/portainer/blob/develop/LICENSE
  title: PortainerCE Status API
  version: 2.39.1
servers:
- url: /api
tags:
- description: Information about the Portainer instance
  name: Status
paths:
  /status:
    get:
      deprecated: true
      description: 'Deprecated: use the `/system/status` endpoint instead.

        Retrieve Portainer status

        **Access policy**: public'
      operationId: StatusInspect
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/system.status'
      summary: Check Portainer status
      tags:
      - Status
components:
  schemas:
    system.status:
      properties:
        InstanceID:
          description: Server Instance ID
          example: 299ab403-70a8-4c05-92f7-bf7a994d50df
          type: string
        Version:
          description: Portainer API version
          example: 2.0.0
          type: string
      type: object
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: X-API-KEY
      type: apiKey
    jwt:
      in: header
      name: Authorization
      type: apiKey
