openapi: 3.2.0
info:
  contact:
    email: info@portainer.io
  description: Portainer API is an HTTP API served by Portainer.
  license:
    name: zlib
    url: https://github.com/portainer/portainer/blob/develop/LICENSE
  title: PortainerCE Edge Groups API
  version: 2.39.1
servers:
- url: /api
tags:
- description: Manage Edge Groups
  name: edge_groups
paths:
  /edge_groups:
    get:
      description: '**Access policy**: administrator'
      operationId: EdgeGroupList
      responses:
        '200':
          description: EdgeGroups
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/edgegroups.decoratedEdgeGroup'
                type: array
        '500':
          description: Internal Server Error
        '503':
          description: Edge compute features are disabled
      security:
      - ApiKeyAuth: []
      - jwt: []
      summary: list EdgeGroups
      tags:
      - edge_groups
    post:
      description: '**Access policy**: administrator'
      operationId: EdgeGroupCreate
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/portainer.EdgeGroup'
        '500':
          description: Internal Server Error
        '503':
          description: Edge compute features are disabled
      security:
      - ApiKeyAuth: []
      - jwt: []
      summary: Create an EdgeGroup
      tags:
      - edge_groups
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/edgegroups.edgeGroupCreatePayload'
        description: EdgeGroup data
        required: true
  /edge_groups/{id}:
    delete:
      description: '**Access policy**: administrator'
      operationId: EdgeGroupDelete
      parameters:
      - description: EdgeGroup Id
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: No Content
        '409':
          description: Edge group is in use by an Edge stack or Edge job
        '500':
          description: Server error
        '503':
          description: Edge compute features are disabled
      security:
      - ApiKeyAuth: []
      - jwt: []
      summary: Deletes an EdgeGroup
      tags:
      - edge_groups
    get:
      description: '**Access policy**: administrator'
      operationId: EdgeGroupInspect
      parameters:
      - description: EdgeGroup Id
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/portainer.EdgeGroup'
        '500':
          description: Internal Server Error
        '503':
          description: Edge compute features are disabled
      security:
      - ApiKeyAuth: []
      - jwt: []
      summary: Inspects an EdgeGroup
      tags:
      - edge_groups
    put:
      description: '**Access policy**: administrator'
      operationId: EdgeGroupUpdate
      parameters:
      - description: EdgeGroup Id
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/portainer.EdgeGroup'
        '500':
          description: Internal Server Error
        '503':
          description: Edge compute features are disabled
      security:
      - ApiKeyAuth: []
      - jwt: []
      summary: Updates an EdgeGroup
      tags:
      - edge_groups
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/edgegroups.edgeGroupUpdatePayload'
        description: EdgeGroup data
        required: true
components:
  schemas:
    roar.Roar-portainer_EndpointID:
      type: object
    edgegroups.edgeGroupCreatePayload:
      properties:
        Dynamic:
          type: boolean
        Endpoints:
          items:
            type: integer
          type: array
        Name:
          type: string
        PartialMatch:
          type: boolean
        TagIDs:
          items:
            type: integer
          type: array
      type: object
    edgegroups.edgeGroupUpdatePayload:
      properties:
        Dynamic:
          type: boolean
        Endpoints:
          items:
            type: integer
          type: array
        Name:
          type: string
        PartialMatch:
          type: boolean
        TagIDs:
          items:
            type: integer
          type: array
      type: object
    edgegroups.decoratedEdgeGroup:
      properties:
        Dynamic:
          type: boolean
        EndpointIds:
          description: Shadow to avoid exposing in the API
          type: integer
        EndpointTypes:
          items:
            $ref: '#/components/schemas/portainer.EndpointType'
          type: array
        Endpoints:
          description: 'Deprecated: only used for API responses'
          items:
            type: integer
          type: array
        HasEdgeJob:
          type: boolean
        HasEdgeStack:
          type: boolean
        Id:
          description: EdgeGroup Identifier
          example: 1
          type: integer
        Name:
          type: string
        PartialMatch:
          type: boolean
        TagIds:
          items:
            type: integer
          type: array
        TrustedEndpoints:
          items:
            type: integer
          type: array
      type: object
    portainer.EdgeGroup:
      properties:
        Dynamic:
          type: boolean
        EndpointIds:
          $ref: '#/components/schemas/roar.Roar-portainer_EndpointID'
        Endpoints:
          description: 'Deprecated: only used for API responses'
          items:
            type: integer
          type: array
        Id:
          description: EdgeGroup Identifier
          example: 1
          type: integer
        Name:
          type: string
        PartialMatch:
          type: boolean
        TagIds:
          items:
            type: integer
          type: array
      type: object
    portainer.EndpointType:
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      type: integer
      x-enum-varnames:
      - _
      - DockerEnvironment
      - AgentOnDockerEnvironment
      - AzureEnvironment
      - EdgeAgentOnDockerEnvironment
      - KubernetesLocalEnvironment
      - AgentOnKubernetesEnvironment
      - EdgeAgentOnKubernetesEnvironment
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: X-API-KEY
      type: apiKey
    jwt:
      in: header
      name: Authorization
      type: apiKey
