openapi: 3.2.0
info:
  contact:
    email: info@portainer.io
  description: Portainer API is an HTTP API served by Portainer.
  license:
    name: zlib
    url: https://github.com/portainer/portainer/blob/develop/LICENSE
  title: PortainerCE Ssl API
  version: 2.39.1
servers:
- url: /api
tags:
- description: Manage ssl settings
  name: SSL
paths:
  /ssl:
    get:
      description: 'Retrieve the ssl settings.

        **Access policy**: administrator'
      operationId: SSLInspect
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/portainer.SSLSettings'
        '400':
          description: Invalid request
        '403':
          description: Permission denied to access settings
        '500':
          description: Server error
      security:
      - ApiKeyAuth: []
      - jwt: []
      summary: Inspect the ssl settings
      tags:
      - SSL
    put:
      description: 'Update the ssl settings.

        **Access policy**: administrator'
      operationId: SSLUpdate
      responses:
        '204':
          description: Success
        '400':
          description: Invalid request
        '403':
          description: Permission denied to access settings
        '500':
          description: Server error
      security:
      - ApiKeyAuth: []
      - jwt: []
      summary: Update the ssl settings
      tags:
      - SSL
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ssl.sslUpdatePayload'
        description: SSL Settings
        required: true
components:
  schemas:
    portainer.SSLSettings:
      properties:
        certPath:
          type: string
        httpEnabled:
          type: boolean
        keyPath:
          type: string
        selfSigned:
          type: boolean
      type: object
    ssl.sslUpdatePayload:
      properties:
        Cert:
          description: SSL Certificates
          type: string
        HTTPEnabled:
          type: boolean
        Key:
          type: string
      type: object
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: X-API-KEY
      type: apiKey
    jwt:
      in: header
      name: Authorization
      type: apiKey
