openapi: 3.2.0
info:
  contact:
    email: info@portainer.io
  description: Portainer API is an HTTP API served by Portainer.
  license:
    name: zlib
    url: https://github.com/portainer/portainer/blob/develop/LICENSE
  title: PortainerCE Upload API
  version: 2.39.1
servers:
- url: /api
tags:
- description: Upload files
  name: Upload
paths:
  /upload/tls/{certificate}:
    post:
      description: 'Use this environment(endpoint) to upload TLS files.

        **Access policy**: administrator'
      operationId: UploadTLS
      parameters:
      - description: TLS file type. Valid values are 'ca', 'cert' or 'key'.
        in: path
        name: certificate
        required: true
        schema:
          type: string
          enum:
          - ca
          - cert
          - key
      responses:
        '204':
          description: Success
        '400':
          description: Invalid request
        '500':
          description: Server error
      security:
      - ApiKeyAuth: []
      - jwt: []
      summary: Upload TLS files
      tags:
      - Upload
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                folder:
                  type: string
                  description: Folder where the TLS file will be stored. Will be created if not existing
                file:
                  type: string
                  description: The file to upload
                  format: binary
              required:
              - folder
              - file
components:
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: X-API-KEY
      type: apiKey
    jwt:
      in: header
      name: Authorization
      type: apiKey
