openapi: 3.2.0
info:
  contact:
    email: info@portainer.io
  description: Portainer API is an HTTP API served by Portainer.
  license:
    name: zlib
    url: https://github.com/portainer/portainer/blob/develop/LICENSE
  title: PortainerCE Intel API
  version: 2.39.1
servers:
- url: /api
tags:
- description: Manage Intel AMT settings
  name: Intel
paths:
  /open_amt:
    post:
      deprecated: true
      description: 'Enable Portainer''s OpenAMT capabilities

        **Access policy**: administrator'
      operationId: OpenAMTConfigure
      responses:
        '204':
          description: Success
        '400':
          description: Invalid request
        '403':
          description: Permission denied to access settings
        '500':
          description: Server error
      security:
      - jwt: []
      summary: Enable Portainer's OpenAMT capabilities
      tags:
      - Intel
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/openamt.openAMTConfigurePayload'
        description: OpenAMT Settings
        required: true
  /open_amt/{id}/activate:
    post:
      deprecated: true
      description: 'Activate OpenAMT device and associate to agent endpoint

        **Access policy**: administrator'
      operationId: openAMTActivate
      parameters:
      - description: Environment identifier
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Success
        '400':
          description: Invalid request
        '403':
          description: Permission denied to access settings
        '500':
          description: Server error
      security:
      - jwt: []
      summary: Activate OpenAMT device and associate to agent endpoint
      tags:
      - Intel
  /open_amt/{id}/devices:
    get:
      deprecated: true
      description: 'Fetch OpenAMT managed devices information for endpoint

        **Access policy**: administrator'
      operationId: OpenAMTDevices
      parameters:
      - description: Environment(Endpoint) identifier
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Success
        '400':
          description: Invalid request
        '403':
          description: Permission denied to access settings
        '500':
          description: Server error
      security:
      - jwt: []
      summary: Fetch OpenAMT managed devices information for endpoint
      tags:
      - Intel
  /open_amt/{id}/devices/{deviceId}/action:
    post:
      deprecated: true
      description: 'Execute out of band action on an AMT managed device

        **Access policy**: administrator'
      operationId: DeviceAction
      parameters:
      - description: Environment identifier
        in: path
        name: id
        required: true
        schema:
          type: integer
      - description: Device identifier
        in: path
        name: deviceId
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: Success
        '400':
          description: Invalid request
        '403':
          description: Permission denied to access settings
        '500':
          description: Server error
      security:
      - jwt: []
      summary: Execute out of band action on an AMT managed device
      tags:
      - Intel
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/openamt.deviceActionPayload'
        description: Device Action
        required: true
  /open_amt/{id}/devices_features/{deviceId}:
    post:
      deprecated: true
      description: 'Enable features on an AMT managed device

        **Access policy**: administrator'
      operationId: DeviceFeatures
      parameters:
      - description: Environment identifier
        in: path
        name: id
        required: true
        schema:
          type: integer
      - description: Device identifier
        in: path
        name: deviceId
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: Success
        '400':
          description: Invalid request
        '403':
          description: Permission denied to access settings
        '500':
          description: Server error
      security:
      - jwt: []
      summary: Enable features on an AMT managed device
      tags:
      - Intel
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/openamt.deviceFeaturesPayload'
        description: Device Features
        required: true
  /open_amt/{id}/info:
    get:
      deprecated: true
      description: 'Request OpenAMT info from a node

        **Access policy**: administrator'
      operationId: OpenAMTHostInfo
      parameters:
      - description: Environment identifier
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Success
        '400':
          description: Invalid request
        '403':
          description: Permission denied to access settings
        '500':
          description: Server error
      security:
      - jwt: []
      summary: Request OpenAMT info from a node
      tags:
      - Intel
components:
  schemas:
    portainer.OpenAMTDeviceEnabledFeatures:
      properties:
        IDER:
          type: boolean
        KVM:
          type: boolean
        SOL:
          type: boolean
        redirection:
          type: boolean
        userConsent:
          type: string
      type: object
    openamt.openAMTConfigurePayload:
      properties:
        CertFileContent:
          type: string
        CertFileName:
          type: string
        CertFilePassword:
          type: string
        DomainName:
          type: string
        Enabled:
          type: boolean
        MPSPassword:
          type: string
        MPSServer:
          type: string
        MPSUser:
          type: string
      type: object
    openamt.deviceFeaturesPayload:
      properties:
        Features:
          $ref: '#/components/schemas/portainer.OpenAMTDeviceEnabledFeatures'
      type: object
    openamt.deviceActionPayload:
      properties:
        Action:
          type: string
      type: object
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: X-API-KEY
      type: apiKey
    jwt:
      in: header
      name: Authorization
      type: apiKey
